<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>

<script type="text/javascript" src="<?php echo $this->getSkinUrl("js/jquery.fancybox.js?v=2.1.5") ?>"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl("js/jquery.fancybox.css?v=2.1.5") ?>" media="screen" />
<script type="text/javascript">
	jQuery(document).ready(function() {
		jQuery('.fancybox').fancybox();
		jQuery("#fancybox-manual-c").click(function() {
			jQuery.fancybox.open([
			], {
				
			});
		});
		
   	});
	function popupcloseme(){
		console.log('close button called');
		jQuery.fancybox.close();
	}
   
</script>


<?php
	$_helper = $this->helper('catalog/output');
	$_product = $this->getProduct();
	$theme = $this->helper('ultimo');
	$helperThis = $this->helper('ultimo/template_catalog_product_view');
	$helperSnippets = $this->helper('ultimo/rsnippets');

	//CSS classes based on product type
	$productTypeId = $_product->getTypeId();
	$productTypeClasses = '';
	if ($productTypeId === 'grouped') {
		$productTypeClasses .= ' is-type-grouped';
	}

	//
	$shortDescription = $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description');

	//Rich snippets
	$useRichSnippets = ($helperSnippets->isEnabledOnProductPage() && $productTypeId !== 'grouped');
	$priceProperties = '';
	if ($useRichSnippets)
	{
		$priceProperties = $helperSnippets->getPriceProperties($_product); //Has to be called before getOfferItemscope
	}

	//Get grid classes for product page sections
	$grid = $helperThis->getGridClasses();

	//Product collaterals
	//--------------------------------------------------------------
	$section = array();
	$relatedProductsHtml = '';
	$upsellProductsHtml = '';
	
	//Related products.
	//If related products not assigned to collateral data container.
	if (!$theme->getCfg('product_page/collateral_related'))
	{
		$replaceRelated = $theme->getCfg('product_page/replace_related');
		if ($replaceRelated == 1) //don't replace with static block
		{
			if ($tmpHtml = trim($this->getChildHtml('related_products_wrapper')))
				$relatedProductsHtml = $tmpHtml;
			//$relatedProductsHtml = trim($this->getChildHtml('related_products_wrapper'));
		}
		elseif ($replaceRelated == 2) //if related is empty, replace with static block
		{
			if ($tmpHtml = trim($this->getChildHtml('related_products_wrapper')))
				$relatedProductsHtml = $tmpHtml;
			else //related empty
				if ($tmpHtml = $this->getChildHtml('block_product_replace_related'))
					$relatedProductsHtml = '<div class="block_product_replace_related">'. $tmpHtml .'</div>';
		}
		elseif ($replaceRelated == 3) //replace with static block
		{
			if ($tmpHtml = $this->getChildHtml('block_product_replace_related'))
				$relatedProductsHtml = '<div class="block_product_replace_related">'. $tmpHtml .'</div>';
		}
	}

	//Up-sell products.
	//If up-sell products not assigned to collateral data container.
	if (!$theme->getCfg('product_page/collateral_upsell'))
	{
		$replaceUpsell = $theme->getCfg('product_page/replace_upsell');
		if ($replaceUpsell == 1) //don't replace with static block
		{
			if ($tmpHtml = trim($this->getChildHtml('upsell_products_wrapper')))
				$upsellProductsHtml = $tmpHtml;
			//$upsellProductsHtml = $this->getChildHtml('upsell_products_wrapper');
		}
		elseif ($replaceUpsell == 2) //if upsell is empty, replace with static block
		{
			if ($tmpHtml = trim($this->getChildHtml('upsell_products_wrapper')))
				$upsellProductsHtml = $tmpHtml;
			else //upsell empty
				if ($tmpHtml = $this->getChildHtml('block_product_replace_upsell'))
					$upsellProductsHtml = '<div class="block_product_replace_upsell">'. $tmpHtml .'</div>';
		}
		elseif ($replaceUpsell == 3) //replace with static block
		{
			if ($tmpHtml = $this->getChildHtml('block_product_replace_upsell'))
				$upsellProductsHtml = '<div class="block_product_replace_upsell">'. $tmpHtml .'</div>';
		}
	}

	//Assign blocks to selected position
	$p = array();

	//Related products
	$position = $theme->getCfg('product_page/related_position');
	if (isset($p[$position]))
		$p[$position] = $p[$position] . $relatedProductsHtml;
	else
		$p[$position] = $relatedProductsHtml;

	//Up-sell products
	$position = $theme->getCfg('product_page/upsell_position');
	if (isset($p[$position]))
		$p[$position] = $p[$position] . $upsellProductsHtml;
	else
		$p[$position] = $upsellProductsHtml;

	//Product collateral data (displayed as tabs or stacked blocks)
	$position = $theme->getCfg('product_page/collateral_position');
	if (isset($p[$position]))
		$p[$position] = $p[$position] . $this->getChildHtml('productCollaterals');
	else
		$p[$position] = $this->getChildHtml('productCollaterals');
?>

<script type="text/javascript">
	var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view nested-container" <?php if ($useRichSnippets) echo $helperSnippets->getProductItemscope(); ?>>

	
		<div class="no-display">
			<input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
			<input type="hidden" name="related_product" id="related-products-field" value="" />
		</div>

		<div class="product-img-column <?php echo $grid['imgCol']; ?>">

			<?php echo $this->getChildHtml('media') ?>
			<?php echo $this->helper('ultimo/labels')->getLabels($_product); //Product labels ?>
			<?php echo $this->getChildHtml('container_product_image_1'); ?>

		</div>
		
		<div class="product-primary-column product-shop <?php echo $grid['primCol']; ?>">

			<div class="product-name">
				<h1 itemprop="name"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
			</div>
			
			<div class="product-name product-brand">
				<span><?php echo $_helper->productAttribute($_product, $_product->getVendor(), 'vendor') ?></span>
			</div> 
			
			<?php echo $this->getReviewsSummaryHtml($_product, false, true); //reviews ?>

			<?php if ($shortDescription): ?>
				<div class="short-description"><div class="std" itemprop="description"><?php echo $shortDescription; ?></div></div>
			<?php endif;?>
			<?php echo $this->getChildHtml('container_product_primary_1'); ?>

			<?php if (isset($p['primCol_1'])) echo $p['primCol_1']; ?>

			<?php if ($sku = $_product->getSku()): ?>
				<?php if ($theme->getCfg('product_page/sku')): ?>
					<div class="sku">
						<span class="label"><?php echo $this->__('SKU'); ?>: </span>
						<span class="value"><?php echo $sku; ?></span>
					</div>
				<?php endif; ?>
				<?php if ($useRichSnippets): ?><meta itemprop="productID" content="sku:<?php echo $sku; ?>" /><?php endif; ?>
			<?php endif; ?>

			<?php echo $this->getChildHtml('alert_urls'); //alerts ?>
			
			<?php if ($extrahint_html = $this->getChildHtml('extrahint')): //qty increments ?>
				<div class="extrahint-wrapper"><?php echo $extrahint_html; ?></div>
			<?php endif; ?>

			<div <?php if ($useRichSnippets) echo $helperSnippets->getOfferItemscope(); ?>>
				<div class="product-type-data<?php echo $productTypeClasses; ?>"><?php echo $this->getChildHtml('product_type_data'); ?></div>
				<?php echo $this->getTierPriceHtml(); ?>
				<?php echo $priceProperties; ?>
			</div> <?php //end: offers ?>
			<form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>

		<?php echo $this->getBlockHtml('formkey'); ?>
			<?php if (!$this->hasOptions()): //add to cart when no options (e.g. simple products) ?>
				<?php if($_product->isSaleable()): ?>
					<div class="add-to-box">
						<?php echo $this->getChildHtml('addtocart') ?>
					</div>
				<?php endif; ?>
				<?php echo $this->getChildHtml('extra_buttons') ?>
			<?php endif; ?>

			<?php if ($_product->isSaleable() && $this->hasOptions()): ?>
				<?php if ($container1_html = $this->getChildChildHtml('container1', '', true, true)): ?>
					<div class="container1-wrapper"><?php echo $container1_html; ?></div>
				<?php endif; ?>
			<?php endif;?>
			
			<?php if ($addtoLinksHtml = $this->getChildHtml('addto')): //compare, wishlist, send to friend ?>
				<div> <!--   class="action-box clearer"> -->
					<?php echo $addtoLinksHtml; ?>
				</div>
			<?php endif; ?>
			<!--  added customization -->
			<div class="clear"></div>
			<?php if ($_product->isSaleable() && $this->hasOptions()): ?>
				<?php if ($container2_html = $this->getChildChildHtml('container2', '', true, true)): ?>
					<div class="box-additional grid12"> <!-- orignal code was <?php echo $grid['cont2Col']; ?> -->
    					<div class="container2-wrapper"><?php echo $container2_html; ?></div>
    				</div>
					
    			<?php endif; ?>
    		<?php endif; ?>
    		<div class="clear"></div>
			<!--  added customization -->
			
			<!--  added new customization -->
			
			<!--<?php // if($fitguide=$_product->getFitguide()) { ?> 
			<?php // $fitguide=Mage::getModel('fitguide/fitguide')->load($fitguide); ?>
			
			<div id="inline1" style="width:600px;display: none;">
				<?php //echo $fitguide->getContent();?>			
			</div> -->
			
			<?php 
			if($_product->getTypeId() == 'simple' ){
			$custom_measurement = $_product->getResource()->getAttribute('custom_measurement')->getFrontend()->getValue($_product); 
			if($custom_measurement == 'Yes'){ ?>
				<a class="fancybox customize-link" href="#inline3" style="margin-left: 0px;">Customize</a>
				<div id="inline3" style="max-width:600px; width:100%;display: none;">	  
					<div class="fieldset custom-size-chart">					
						<div class="customize-your-product-image">
							<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('customize-your-product-image')->toHtml(); ?>
						</div>
						<h2 class="legend">Customize Your Product</h2>
						<div class="customize-your-product-option">
							<ul class="product-custom-option form-list">
								<li class="fields">
									<div class="field">
										<label for="bust_chest">Bust/Chest</label>
										<div class="input-box">
											<input type="text" class="input-text product-custom-option" name="bust_chest" value="">
										</div>
									</div>
									<div class="field">
										<label for="waist">Waist</label>
										<div class="input-box">
											<input type="text" class="input-text  product-custom-option" name="waist" value="">
										</div>
									</div>
								</li>
								<li class="fields">
									<div class="field">
										<label for="sleeve_length">Sleeve Length</label>
										<div class="input-box">
											<input type="text" class="input-text  product-custom-option" name="sleeve_length" value="">
										</div>
									</div>
									<div class="field">
										<label for="shoulders">Shoulders</label>
										<div class="input-box">
											<input type="text" class="input-text  product-custom-option" name="shoulders" value="">
										</div>
									</div>
								</li>
								<li class="fields">
									<div class="field">
										<label for="armhole">Armhole</label>
										<div class="input-box">
											<input type="text" class="input-text  product-custom-option" name="armhole" value="">
										</div>
									</div>
									<div class="field">
										<label for="neck">Neck</label>
										<div class="input-box">
											<input type="text" class="input-text  product-custom-option" name="neck" value="">
										</div>
									</div>
								</li>
								<li class="fields">
									<div class="field">
										<label for="length">Length</label>
										<div class="input-box">
											<input type="text" class="input-text  product-custom-option" name="length" value="">
										</div>
									</div>
								
									<div class="field">
										<label for="hip">Hip</label>
										<div class="input-box">
											<input type="text" class="input-text  product-custom-option" name="hip" value="">
										</div>
									</div>
								</li>
								<li class="fields">
									<div class="field">
										<label for="length_shoulder_to_nee">Length (Shoulder to Knee)</label>
										<div class="input-box">
											<input type="text" class="input-text  product-custom-option" name="length_shoulder_to_nee" value="">
										</div>
									</div>
								
									<div class="field">
										<label for="length_waist_to_ankle">Length (Waist to Ankle)</label>
										<div class="input-box">
											<input type="text" class="input-text  product-custom-option" name="length_waist_to_ankle" value="">
										</div>
									</div>
								</li>
							</ul>
							<a href="#" title="Submit" class="button" onclick="popupcloseme();"><span><span>Submit</span></span></a>
						</div>
						
					</div>						
				</div>
			<?php }	?>
			<?php }	?>
			
			<!--  End: added new customization -->
			
			
			<?php if (isset($p['primCol_2'])) echo $p['primCol_2']; ?>

			<?php echo $this->getChildHtml('other'); ?>

			<?php echo $this->getChildHtml('container_product_primary_2'); ?>
			</form>
			<div class="box-additional "><!--< ?php echo $grid['lowerPrimCol']; ?>-->

						<?php if (isset($p['lowerPrimCol_1'])) echo $p['lowerPrimCol_1']; ?>
						
						<?php echo $this->getChildHtml('product_additional_data') ?>
				
						<?php echo $this->getChildHtml('reviews'); //Reviews ?>
				
					</div> <!-- end: box-tabs -->
		</div> <!-- end: product-shop -->
		
		<?php /*if (isset($grid['secCol'])): //(!empty($secondaryColUnits)): ?>

			<div class="product-secondary-column <?php echo $grid['secCol']; ?> custom-sidebar-right">
				<div class="inner">

					

				</div>
			</div> <!-- end: product-secondary-column -->

		<?php endif; ?>

		<?php if ($_product->isSaleable() && $this->hasOptions()): ?>
			<?php if ($container2_html = $this->getChildChildHtml('container2', '', true, true)): ?>
				<div class="box-additional <?php echo $grid['cont2Col']; ?>">
					<div class="container2-wrapper"><?php echo $container2_html; ?></div>
				</div>
			<?php endif; ?>
		<?php endif; */?>

	
	<script type="text/javascript">
	//<![CDATA[
		var productAddToCartForm = new VarienForm('product_addtocart_form');
		productAddToCartForm.submit = function(button, url) {
			if (this.validator.validate()) {
				var form = this.form;
				var oldUrl = form.action;

				if (url) {
				   form.action = url;
				}
				var e = null;
				try {
					this.form.submit();
				} catch (e) {
				}
				this.form.action = oldUrl;
				if (e) {
					throw e;
				}

				if (button && button != 'undefined') {
					button.disabled = true;
				}
			}
		}.bind(productAddToCartForm);

		productAddToCartForm.submitLight = function(button, url){
			if(this.validator) {
				var nv = Validation.methods;
				delete Validation.methods['required-entry'];
				delete Validation.methods['validate-one-required'];
				delete Validation.methods['validate-one-required-by-name'];
				if (this.validator.validate()) {
					if (url) {
						this.form.action = url;
					}
					this.form.submit();
				}
				Object.extend(Validation.methods, nv);
			}
		}.bind(productAddToCartForm);
	//]]>
	</script>

	<?php //Lower primary column ?>
	

	<?php //Lower secondary column ?>
	<?php if (isset($p['lowerSecCol_2'])): ?>
		<div class="box-additional box-sidebar custom-sidebar-right <?php echo $grid['lowerSecCol']; ?>">
			<div class="inner"><?php echo $p['lowerSecCol_2']; ?></div>
		</div>
	<?php endif; ?>

	<?php if (isset($p['lowerPrimCol_2'])): ?>
		<div class="box-additional grid12"><?php echo $p['lowerPrimCol_2']; ?></div>
	<?php endif; ?>

</div> <!-- end: product-view -->

<style>
	.custom-size-chart{
		background:#fff;
		padding:15px 15px 30px;
		width:100%;
		box-sizing:border-box;
	}
	.custom-size-chart.fieldset .legend{
		font-weight: 500;
		font-size: 20px;
		font-family: arial;
		text-transform: uppercase;
		color: #000;     padding-bottom: 15px;
		margin-bottom:20px;
	}
	.custom-size-chart .form-list .field{
		width:48%;
	}
	.custom-size-chart .form-list .field:nth-child(even){
		float:right;
	}
	.custom-size-chart .form-list .field:nth-child(odd){
		float:left;
	}
	.custom-size-chart .form-list label{font-weight:500; font-family: arial; font-size: 13px; color: #000;}
	.custom-size-chart .form-list input.input-text{display:block; width:100%;}

	.customize-your-product-image{
		display:block;
		width:100%;
		margin-bottom:30px;
	}
	.customize-your-product-image img{
		max-width:100%;
	}
	.customize-your-product-option{
		display:block;
		width:100%;
	}
	
	.sizechart-link,
	.customize-link{
		font-size: 12px;
		font-family: arial;
		text-transform: uppercase;
		font-weight: 600;
		color: #aaa;
		display: inline-block;
		line-height: 17px;
		margin: 0;
		padding: 0;
		height: 30px;
		line-height: 30px;
		letter-spacing: 1.1px;
	}
	.sizechart-link{
		color: #aaa;
		margin: 0 10px !important;
		letter-spacing: .5px;
	}
	
	@media (max-width:480px){
		.custom-size-chart .form-list .field{
			width:100%;
			margin-bottom:10px;
		}
	}
	
</style>
