<?php
/**
 * GoMage Social Connector Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2013 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 1.1.0
 * @since        Class available since Release 1.0.0
 */
?>
<script type="text/javascript">
	function firepixel()
	{
	  //fb pixel
		var _fbq = window._fbq || (window._fbq = []);
		if (!_fbq.loaded) {
		  var fbds = document.createElement('script');
		  fbds.async = true;
		  fbds.src = '//connect.facebook.net/en_US/fbds.js';
		  var s = document.getElementsByTagName('script')[0];
		  s.parentNode.insertBefore(fbds, s);
		  _fbq.loaded = true;
		}
		window._fbq = window._fbq || [];
		window._fbq.push(['track', '6024504780717', {'value':'0.00','currency':'USD'}]);
		var _fbq = window._fbq || (window._fbq = []);
				if (!_fbq.loaded) {
				  var fbds = document.createElement('script');
				  fbds.async = true;
				  fbds.src = '//connect.facebook.net/en_US/fbds.js';
				  var s = document.getElementsByTagName('script')[0];
				  s.parentNode.insertBefore(fbds, s);
				  _fbq.loaded = true;
				}
				window._fbq = window._fbq || [];
				window._fbq.push(['track', '6020191795885', {'value':'0.00','currency':'USD'}]);
		
		//jQuery('body').append('<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?ev=6020191795885&amp;cd[value]=0.00&amp;cd[currency]=USD&amp;noscript=1" /></noscript>');
	       
	       //fb pixel
	       
	       google_conversion_id = 958174239;
		google_conversion_language = "en";
		google_conversion_format = "3";
		google_conversion_color = "ffffff";
		google_conversion_label = "gax1CMWevlkQn6jyyAM";
		google_remarketing_only = false;
		var adScript = document.createElement('script');
		adScript.setAttribute('src','//www.googleadservices.com/pagead/conversion.js');
		document.head.appendChild(adScript);
	       
	}
	function firegooglepixel(obj)
	{
		
		 //fb pixel
		var _fbq = window._fbq || (window._fbq = []);
		if (!_fbq.loaded) {
		  var fbds = document.createElement('script');
		  fbds.async = true;
		  fbds.src = '//connect.facebook.net/en_US/fbds.js';
		  var s = document.getElementsByTagName('script')[0];
		  s.parentNode.insertBefore(fbds, s);
		  _fbq.loaded = true;
		}
		window._fbq = window._fbq || [];
		window._fbq.push(['track', '6024504780717', {'value':'0.00','currency':'USD'}]);
		var _fbq = window._fbq || (window._fbq = []);
		if (!_fbq.loaded) {
		  var fbds = document.createElement('script');
		  fbds.async = true;
		  fbds.src = '//connect.facebook.net/en_US/fbds.js';
		  var s = document.getElementsByTagName('script')[0];
		  s.parentNode.insertBefore(fbds, s);
		  _fbq.loaded = true;
		}
		window._fbq = window._fbq || [];
		window._fbq.push(['track', '6020191795885', {'value':'0.00','currency':'USD'}]);
		//jQuery('body').append('<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?ev=6020191795885&amp;cd[value]=0.00&amp;cd[currency]=USD&amp;noscript=1" /></noscript>');
	       
	       //fb pixel
	       
	        google_conversion_id = 958174239;
		google_conversion_language = "en";
		google_conversion_format = "3";
		google_conversion_color = "ffffff";
		google_conversion_label = "gax1CMWevlkQn6jyyAM";
		google_remarketing_only = false;
		var adScript = document.createElement('script');
		adScript.setAttribute('src','//www.googleadservices.com/pagead/conversion.js');
		document.head.appendChild(adScript);
			       
	       

		window.location=jQuery(obj).attr('rel');
	}
</script>
<?php
	$services = Mage::helper('gomage_social')->getServices($this->getPlace());
?>
<?php if (count($services)): ?>
	<?php /*if ($this->getUsedList()): ?><li class="last gs-list"><?php endif; */?>
	<!--<ul class="gs-login <?php //if(Mage::getConfig()->getModuleConfig('Enterprise_Enterprise' )): ?>gs-login-ee<?php //endif; ?> gs-login-<?php //echo $this->getPlace() ?>">-->
		<?php
			end($services);
        $last_type = key($services);
		?>
		<?php foreach ($services as $type => $value): ?>

<?php switch ($type): ?>
<?php case (GoMage_Social_Model_Type::FACEBOOK): ?>
	<?php if ($this->getLoginType('facebook') == GoMage_Social_Model_Adminhtml_System_Config_Source_Login_Type::BUTTON): ?>
			<fb:login-button scope="email" onlogin="gomageSocialFBCheckLogin()" v="2"></fb:login-button>
	<?php else: ?>
        <div class="socialIcon_box">
		<a href="#" onclick="firepixel();gomageSocialFBLogin();return false;" title="Register with your Facebook account" class="fbBlock"><svg class="icon icon-facebook" viewBox="0 0 32 32"><use xlink:href="#icon-facebook"></use></svg>Register with Facebook<?php // echo $this->getText('facebook') ?></a>
        </div>       
	<?php endif;?>
	<!--<li <?php /*if ($type ==  $last_type): ?>class="last"<?php endif; ?>>
		<?php if ($this->getLoginType('facebook') == GoMage_Social_Model_Adminhtml_System_Config_Source_Login_Type::BUTTON): ?>
			<fb:login-button scope="email" onlogin="gomageSocialFBCheckLogin()" v="2"></fb:login-button>
		<?php else: ?>
			<a href="#" onclick="gomageSocialFBLogin();return false;" title="<?php echo $this->getText('facebook') ?>">
				<?php if (($image = $this->getImage('facebook')) && ($this->getLoginType('facebook') == GoMage_Social_Model_Adminhtml_System_Config_Source_Login_Type::IMAGE)): ?>
					<img src="<?php echo $image ?>" alt="<?php echo $this->getText('facebook') ?>" />
				<?php else: ?>
					<?php echo $this->getText('facebook') ?>
				<?php endif; ?>
			</a>
		<?php endif;*/ ?>
	</li>-->
<?php break; ?>
<?php case (GoMage_Social_Model_Type::GOOGLE): ?>
<?php if ($this->getLoginType('google') == GoMage_Social_Model_Adminhtml_System_Config_Source_Login_Type::BUTTON): ?>
			<button class="g-signin"
		        data-scope="https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email"
		        data-requestvisibleactions="http://schemas.google.com/AddActivity"
		        data-clientId="<?php echo Mage::getStoreConfig('gomage_social/google/id') ?>"
		        data-accesstype="offline"
		        data-callback="gomageSocialGSigninCallback"
				data-approvalprompt="force"
		        data-cookiepolicy="single_host_origin"
		        data-height="short">
		    </button>
<?php else: ?>
        <div class="socialIcon_box">
            <a onclick="firegooglepixel(this)" rel="<?php echo $this->getUrl('gomage_social/google/login', array('_secure' => true, 'gs_url' => Mage::helper('core')->urlEncode($this->getUrl('thankyou'))));  ?>"  title="Register with your Google Account" class="gBlock"><svg class="icon icon-googleplus" viewBox="0 0 32 32"><use xlink:href="#icon-googleplus"></use></svg>Register with Google <?php  //echo //$this->getText('google') ?></a>
        </div>    
<?php endif;?>	
	<!--<li <?php if ($type ==  $last_type): ?>class="last"<?php endif; ?>>
		<?php /*if ($this->getLoginType('google') == GoMage_Social_Model_Adminhtml_System_Config_Source_Login_Type::BUTTON): ?>
			<button class="g-signin"
		        data-scope="https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email"
		        data-requestvisibleactions="http://schemas.google.com/AddActivity"
		        data-clientId="<?php echo Mage::getStoreConfig('gomage_social/google/id') ?>"
		        data-accesstype="offline"
		        data-callback="gomageSocialGSigninCallback"
				data-approvalprompt="force"
		        data-cookiepolicy="single_host_origin"
		        data-height="short">
		    </button>
		<?php else: ?>
			<a href="<?php echo $this->getUrl('gomage_social/google/login', array('_secure' => true, 'gs_url' => Mage::helper('core')->urlEncode(Mage::helper('core/url')->getCurrentUrl())));  ?>" title="<?php echo $this->getText('google') ?>">
				<?php if (($image = $this->getImage('google')) && ($this->getLoginType('google') == GoMage_Social_Model_Adminhtml_System_Config_Source_Login_Type::IMAGE)): ?>
					<img src="<?php echo $image ?>" alt="<?php echo $this->getText('google') ?>" />
				<?php else: ?>
					<?php echo $this->getText('google') ?>
				<?php endif; ?>
			</a>
		<?php endif;*/ ?>
	</li>-->
<?php break; ?>
                    <?php case (GoMage_Social_Model_Type::LINKEDIN): ?>
                     <?php echo $this->getServiceBlock($type, $type==  $last_type);?>
                    <?php break; ?>
                    <?php case (GoMage_Social_Model_Type::TWITTER): ?>
                       <?php echo $this->getServiceBlock($type, $type==  $last_type);?>
                        <?php break; ?>
                    <?php case (GoMage_Social_Model_Type::TUMBLR): ?>
                        <?php echo $this->getServiceBlock($type, $type==  $last_type);?>
                        <?php break; ?>
                    <?php case (GoMage_Social_Model_Type::REDDIT): ?>
                        <?php echo $this->getServiceBlock($type, $type==  $last_type);?>
                        <?php break; ?>
<?php endswitch; ?>

		<?php endforeach; ?>
	<!--</ul>
	<?php /*if ($this->getUsedList()): ?></li><?php endif;*/ ?>-->
<?php endif; ?>
